language: haskell
notifications:
  email: false
before_script:
  - cabal configure
  - cabal sdist
  - cd ..
  - tar -xf operational/dist/operational*.tar.gz
  - cd operational*
script:
  - cabal configure --enable-tests && cabal build && cabal test
